name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev liblua5.1-dev
      - name: build game
        run: |
          mkdir build
          cd build
          cmake ..
          make
