name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libsdl2-dev liblua5.1-dev
      - name: build game
        run: |
          mkdir build
          cd build
          cmake ..
          make
